title: "Conor Damery – C++ Game Engine Devlog"
description: "Low-level game engine development, rendering, and systems programming in C++"
baseurl: "/devlog"
url: "https://belfer.github.io"

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed

permalink: /:categories/:title/