title: "Game Engine Devlog"
description: "Low-level game engine development, rendering, and systems programming."
baseurl: "/devlog"
url: "https://belfer.github.io"

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed

permalink: /:categories/:year/:month/:day/:title/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post