title: "C++ Game Engine Blog"
description: "Low-level game engine development, rendering, and systems programming in C++"
baseurl: "/dev-blog"
url: "https://belfer.github.io"

markdown: kramdown

plugins:
  - jekyll-feed

permalink: /:categories/:title/